### ISSUE TITLE
Searching in Object Explorer doesn't show the correct results for inherited classes

### ISSUE THREAD

**Issue by DGh0st** [Flipboard/FLEX#363]
Search results always show properties/methods/etc of the initial class only, no matter what is selected in the carousel. I would expect the results to be the class that is selected in the carousel (or include the class selected at the very least), which I was available to achieve by swapping the order of first two if statements in https://github.com/Flipboard/FLEX/blob/a3f66b3f87820568788132ad05aa9035d821aacb/Classes/Core/FLEXTableViewController.m#L114-L117

I am not sure what other side effects it has but I changed this:
```objc
- (NSInteger)selectedScope {
    if (self.searchController.searchBar.showsScopeBar) {
        return self.searchController.searchBar.selectedScopeButtonIndex;
    } else if (self.showsCarousel) {
        return self.carousel.selectedIndex;
    } else {
        return NSNotFound;
    }
}
```
to
```objc
- (NSInteger)selectedScope {
    if (self.showsCarousel) {
        return self.carousel.selectedIndex;
    } else if (self.searchController.searchBar.showsScopeBar) {
        return self.searchController.searchBar.selectedScopeButtonIndex;
    } else {
        return NSNotFound;
    }
}
```

**Comment by NSExceptional** [comment]
If you're using libflex in Cydia, I submitted an update to BigBoss yesterday. This was fixed in 3.1.1. And if you're using FLEX itself, `pod update FLEX`

Basically, the search controller was setting `showsScopeBar` to `YES` even though there are no scope titles. I think it's a bug in iOS 13. I worked around it somehow.

**Comment by DGh0st** [comment]
Still seeing the issue with libflex, and also tried the latest commit which has same behavior.

Here is the reproduction steps just to make it more clear:
1) Open object explorer for a view
2) Search for a method that is part of that class only (for instance `initWithFrame:`)
3) Select `NSObject` from the carousel (which shouldn't have `initWithFrame:`)
4) The results are still showing for the original class (not the selected inherited one)
5) Typing something else in the text field shows results of the original class as well

**Comment by NSExceptional** [comment]
[I cannot reproduce this in the latest version of libFLEX.](https://streamable.com/4xt17) Are you sure you're on the right version? Did you respring after? Which app are you trying it in?

**Comment by DGh0st** [comment]
Yeah I have resprung a few times, tried on iOS 12.4.3 and 13.2.2.

I have tried these versions:
FLEXing 1.1.0
libFLEX 3.1.1

and trying to build on my own with the latest revision (both don't work).

[Here is what I see on iOS 13.2.2 iPad 6 in Calendar app](https://streamable.com/ylot9)

**Comment by DGh0st** [comment]
Hmm, its working now after doing a clean setup. Something must have been corrupt after updating. But I still don't understand why doing a clean setup earlier didn't work, anyways its working now so going to close this.
