### ISSUE TITLE
Resolve warning from unused typedef

### ISSUE THREAD

**Issue by tijoinc** [Flipboard/FLEX#73]
Shows up when building with Xcode 7

https://github.com/Flipboard/FLEX/blob/master/Classes/Network/PonyDebugger/FLEXNetworkObserver.m#L871

**Comment by ryanolsonk** [comment]
Resolved in #76

**Comment by tijoinc** [comment]
@ryanolsonk actually, I don't believe https://github.com/Flipboard/FLEX/pull/76 resolves this. I'm still seeing [this](https://github.com/Flipboard/FLEX/blob/master/Classes/Network/PonyDebugger/FLEXNetworkObserver.m#L870) unused `typedef` on master.

**Comment by tijoinc** [comment]
Opened a PR to resolve in https://github.com/Flipboard/FLEX/pull/77.
